[global]
excludes = [
  "node_modules/**",
  "**/node_modules/**",
  ".plasmo/**",
  "build/**",
  "**/.next/**",
  "**/out/**",
  "dist/**",
  "bun.lockb",
  "bun.lock",
  "packages/landing/next-env.d.ts",
]

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
  "*.ts",
  "*.tsx",
  "*.js",
  "*.jsx",
  "*.mjs",
  "*.cjs",
  "*.css",
  "*.json",
  "*.md",
  "*.yaml",
  "*.yml",
]
